// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-hXoXi_Fe18PX6hoyPSvUAg8kOdubGyI',
    appId: '1:6231932116:web:39dbca8f26649654368f41',
    messagingSenderId: '6231932116',
    projectId: 'e-commerce-practise-project',
    authDomain: 'e-commerce-practise-project.firebaseapp.com',
    storageBucket: 'e-commerce-practise-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCptdPmz797sSwnVnSsbHI_9gWPvrsUQHY',
    appId: '1:6231932116:android:5f059e88307f95f4368f41',
    messagingSenderId: '6231932116',
    projectId: 'e-commerce-practise-project',
    storageBucket: 'e-commerce-practise-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2L0V36yXzFQ0aLOX9XR0JoUybk_bkMZU',
    appId: '1:6231932116:ios:68274a24668b0b9e368f41',
    messagingSenderId: '6231932116',
    projectId: 'e-commerce-practise-project',
    storageBucket: 'e-commerce-practise-project.appspot.com',
    iosClientId: '6231932116-c7ho229hm7ompfl6a8akdn0s5e0hftsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceFlutterWell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2L0V36yXzFQ0aLOX9XR0JoUybk_bkMZU',
    appId: '1:6231932116:ios:68274a24668b0b9e368f41',
    messagingSenderId: '6231932116',
    projectId: 'e-commerce-practise-project',
    storageBucket: 'e-commerce-practise-project.appspot.com',
    iosClientId: '6231932116-c7ho229hm7ompfl6a8akdn0s5e0hftsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceFlutterWell',
  );
}
